runtime: python310
entrypoint: gunicorn -b :$PORT project.wsgi

instance_class: F2

env_variables:
  DJANGO_SETTINGS_MODULE: "project.settings"
  PYTHONUNBUFFERED: "true"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto
