# Generated by Django 4.0.6 on 2022-07-31 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoahDDBB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_poster',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_streaming',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_movie',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_trailer',
            field=models.CharField(max_length=100),
        ),
    ]
