# Generated by Django 4.0.6 on 2022-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoahDDBB', '0002_alter_movies_mov_director_alter_movies_mov_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_director',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_language',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_poster',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_streaming',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_movie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_trailer',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
