# Generated by Django 4.0.6 on 2022-07-31 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoahDDBB', '0003_alter_movies_mov_country_alter_movies_mov_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='mov_rating',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
