# Generated by Django 4.0.6 on 2022-12-14 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shoahDDBB', '0006_alter_movies_mov_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='mov_country',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_language',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_poster',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('NC-17', 'NC-17'), ('Unrated', 'Unrated')], default='PG', max_length=10),
        ),
        migrations.AlterField(
            model_name='movies',
            name='mov_streaming',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_movie',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='movies',
            name='url_trailer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='Commentaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('commentary', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoahDDBB.movies')),
            ],
        ),
    ]
